# Generated by Django 5.1 on 2024-09-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('K_app', '0002_category_tag_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
