# Generated by Django 5.1 on 2024-10-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('K_app', '0004_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='name',
            new_name='username',
        ),
    ]
