# Generated by Django 4.2.7 on 2024-12-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('K_app', '0006_remove_master_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='username',
            new_name='name',
        ),
    ]
